[project]
name = "cgo-26-ae"
version = "0.1.0"
description = "CGO 2026 Artifact for Proton"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bitsandbytes>=0.48.2",
    "brokenaxes",
    "datasets>=4.0.0",
    "kernels",
    "llnl-hatchet>=2025.1.1",
    "matplotlib>=3.10.7",
    "pytest>=8.4.2",
    "triton",
    "torch",
    "torchvision",
    "unsloth>=2025.11.1",
    "unsloth-zoo>=2025.11.2",
]

[tool.uv]
override-dependencies = [
    "xformers; sys_platform == 'never'",
]

[tool.uv.sources]
triton = { path = "../../submodules/triton" }
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

