[project]
name = "cgo-26-ae"
version = "0.1.0"
description = "CGO 2026 Artifact for Proton"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llnl-hatchet>=2025.1.1",
    "matplotlib>=3.10.7",
    "pytest>=8.4.2",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "triton",
]

[tool.uv.sources]
triton = { path = "./submodules/triton", editable = true}
