[project]
name = "cgo-26-ae"
version = "0.1.0"
description = "CGO 2026 Artifact for Proton"
readme = "README.md"
requires-python = "==3.13.1"
dependencies = [
    "bitsandbytes @ https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_main/bitsandbytes-1.33.7.preview-py3-none-manylinux_2_24_x86_64.whl",
    "brokenaxes",
    "datasets",
    "kernels",
    "llnl-hatchet>=2025.1.1",
    "matplotlib>=3.10.7",
    "pytest>=8.4.2",
    "triton",
    "torch @ https://download.pytorch.org/whl/rocm6.4/torch-2.9.0%2Brocm6.4-cp313-cp313-manylinux_2_28_x86_64.whl",
    "torchvision @ https://download.pytorch.org/whl/rocm6.4/torchvision-0.24.0%2Brocm6.4-cp313-cp313-manylinux_2_28_x86_64.whl",
    "unsloth-zoo",
    "unsloth",
]

[tool.uv]
override-dependencies = [
    "xformers; sys_platform == 'never'",
    "pytorch-triton-rocm; sys_platform == 'never'",
]


[tool.uv.sources]
triton = { path = "../../submodules/triton" }
